import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Matheus Gaston - Portfolio',
  description: 'Generated by create next app',
  icons: {
    icon: '/'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <html lang="en">
    <body className={inter.className}>
      <NavBar />
      <main className='pt-2'>{children}</main>
    </body>
  </html>
)
}